# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a36c569d6d4ce972beceb49bca0a12eb3e4009b3f3d3135662ca92d21be021ecaa9263b04ff4ad39b4028bdd9aaf6e0104a2d63b65decb497744efd8296a694

test:
  secret_key_base: a28cd515b0c4ab2ddc912234db328c4111761960d0433d357a9e1e82ad8b4b1f27e4096a2f2e9e7d54520645cd13d20579db4d99b8a77086549e527a4bce8880

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
